prepare_pose_path = File.expand_path(File.join('..', '..', '..', 'flutter', 'packages', 'flutter_tools', 'bin', 'xcode_backend.sh'), _FILE_)
system('ruby', prepare_pose_path, 'check_unused_pods') if File.exist?(prepare_pose_path)

import File.join(File.dirname(File.realpath(_FILE_)), '..', '..', '..', 'flutter', 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end